// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vault.Database;

#nullable disable

namespace Vault.Migrations
{
    [DbContext(typeof(VaultContext))]
    [Migration("20260328160124_AddNotesEmulatorFields")]
    partial class AddNotesEmulatorFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Vault.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FingerprintProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IntroEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("IntroStart")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OutroStart")
                        .HasColumnType("REAL");

                    b.Property<long>("ResumePositionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Vault.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxArtPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emulator")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FileSizeGB")
                        .HasColumnType("REAL");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HltbComplete")
                        .HasColumnType("REAL");

                    b.Property<int>("HltbCompletionist")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HltbMain")
                        .HasColumnType("REAL");

                    b.Property<int>("HltbMainPlusExtra")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HltbMainSides")
                        .HasColumnType("REAL");

                    b.Property<int>("HltbMainStory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWishlist")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManuallyMarkedNotDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaytimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetroAchievementsGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Vault.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResumePositionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbIds")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WatchStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchedEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Vault.Models.Episode", b =>
                {
                    b.HasOne("Vault.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });
#pragma warning restore 612, 618
        }
    }
}
